### ISSUE TITLE
Consider adding README documentation

### ISSUE THREAD

**Issue by thosakwe** [thislooksfun/angel_compiled_mustache#11]
Sorry to be nit-picky, haha...

One of my goals for Angel and its surrounding ecosystem is to always provide documentation for functionality.

The documentation can be short for a package like this; check out the README for `angel_mustache`:

https://github.com/angel-dart/mustache

**Comment by thislooksfun** [comment]
No worries, it's great to have someone interested! Having some docs in the readme is a good idea.
