### ISSUE TITLE
Potentially consider using package:file instead dart:io

### ISSUE THREAD

**Issue by thosakwe** [thislooksfun/angel_compiled_mustache#4]
Hi! Thanks so much for your contribution to the Angel ecosystem. This is the first Angel package on `pub`, other than the official ones.

One thing that you might consider is replacing the use of the `dart:io` filesystem API with `package:file`:

1. It's pluggable/mockable, and therefore better-suited for testing
2. Almost exactly the same API
3. `package:file` is used in Angel 1.1.0 plugins, and 1.1.0 is almost ready to launch

Thanks again for your contribution!

**Comment by thislooksfun** [comment]
That's awesome, I had no idea I was the first! I'm sure I won't be the last though!

I've taken your suggestion and reworked it to (mostly) use `package:file` instead of `dart:io`, and released v1.1.0. If you have any more ideas/suggestions, please don't hesitate to reach out!
